name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login DockerHub
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build & Push
      run: |
        IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/demo-nginx
        docker build -t $IMAGE:${{ github.sha }} .
        docker push $IMAGE:${{ github.sha }}

    - name: Update GitOps Repo
      run: |
        git clone https://x-access-token:${{ secrets.GITOPS_TOKEN }}@github.com/xiaoxiedocker-hue/gitops-repo.git
        cd gitops-repo/apps/nginx

        sed -i "s|image:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/demo-nginx:${{ github.sha }}|" deployment.yaml

        git config user.name "github-actions"
        git config user.email "actions@github.com"

        git commit -am "update image"
        git push
